-- Your code here 
INSERT INTO customers (name, email, phone_number) VALUES('Monica', 'monica@friends.show', 2222222222);
INSERT INTO customers (name, phone_number) VALUES('Rachel', 1111111111);
SELECT points FROM customers WHERE name = 'Rachel';
UPDATE customers SET points = 5 + 1 WHERE name = 'Rachel';
SELECT points FROM customers WHERE name = 'Rachel';
INSERT INTO coffee (is_redeemed, ordered_at) VALUES (0, CURRENT_TIMESTAMP);
INSERT INTO customers (name, email, phone_number) VALUES('Phoebe', 'phoebe@friends.show', 3333333333);
UPDATE customers SET points = 5 + 3 WHERE name = 'Phoebe';
UPDATE customers SET points = 6 + 4 WHERE name = 'Rachel';
UPDATE customers SET points = 5 + 4 WHERE name = 'Monica';
SELECT points FROM customers WHERE name = 'Monica';
INSERT INTO coffee (is_redeemed, ordered_at) VALUES (0, CURRENT_TIMESTAMP);
SELECT points FROM customers WHERE name = 'Rachel';
INSERT INTO coffee (is_redeemed, ordered_at) VALUES (1, CURRENT_TIMESTAMP);
UPDATE customers SET points = 0 WHERE name = 'Rachel';
INSERT INTO customers (name, email) VALUES('Joey', 'joey@friends.show');
INSERT INTO customers (name, email) VALUES('Chandler', 'chandler@friends.show');
INSERT INTO customers (name, email) VALUES('Ross', 'ross@friends.show');
INSERT INTO coffee (is_redeemed, ordered_at) VALUES (0, CURRENT_TIMESTAMP);
UPDATE customers SET points = 5 + 6 WHERE name = 'Ross';
UPDATE customers SET points = 9 + 3 WHERE name = 'Monica';
DELETE FROM coffee WHERE id = 19;
DELETE FROM coffee WHERE id = 20;
UPDATE customers SET points = 11 - 2 WHERE name = 'Ross';
UPDATE customers SET points = 5 + 2 WHERE name = 'Joey';
UPDATE customers SET points = 12 - 10 WHERE name = 'Monica';
DELETE FROM customers WHERE name = 'Chandler';
UPDATE customers SET points = 9 + 1 WHERE name = 'Ross';
UPDATE customers SET points = 7 + 1  WHERE name = 'Joey';