version: '3'

services:
  drupal:
    build: .
    image: sydney/custom-drupal
    ports:
      - 8080:80
    depends_on:
      - "postgres"

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD="password"
      # - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - drupal-data:/var/lib/postgresql/data

volumes:
  drupal-data:
